<?php

/* Generated by chatGPT 4o */

function parseCustomFormat($content) {
    //Convert single newlines to paragraph tags
    $content = preg_replace("/\n/", "</p><p>", $content);
    return "<p>" . $content . "</p>";
}

function getContent($file) {
    $file = realpath(urldecode($file));
    if (strpos($file, realpath(__DIR__ . '/Data')) === 0 && file_exists($file)) {
        if (pathinfo($file, PATHINFO_EXTENSION) == 'txt') {
            return '';
        }
        $content = file_get_contents($file);
        return parseCustomFormat($content);
    }
    return '';
}

function getDefaultContent($folder) {
    $defaultFile = realpath(__DIR__ . '/Data/' . urldecode($folder) . '/index');
    if (file_exists($defaultFile)) {
        $content = file_get_contents($defaultFile);
        return parseCustomFormat($content);
    }
    return '';
}

function getImagesContent($folder) {
    $folderPath = realpath(__DIR__ . '/Data/' . urldecode($folder));
    $imageTypes = ['png', 'jpg', 'jpeg', 'gif'];
    $imagesHtml = '';

    if (is_dir($folderPath)) {
        $files = scandir($folderPath);
        $addontext = '';
        foreach ($files as $file) {
            $ext = pathinfo($file, PATHINFO_EXTENSION);
            if ($file == 'additional.txt') {
                $addontext = nl2br(file_get_contents(realpath(__DIR__. '/Data/' . urldecode($folder) . '/additional.txt')));
                $imagesHtml = $addontext . $imagesHtml;
            }
            if (in_array(strtolower($ext), $imageTypes)) {
                $relativePath = str_replace(realpath($_SERVER['DOCUMENT_ROOT']), '', $folderPath . DIRECTORY_SEPARATOR . $file);
                $relativePath = str_replace('\\', '/', $relativePath);
                $encodedPath = rawurlencode($relativePath);
                $encodedPath = str_replace('%2F', '/', $encodedPath);
                $imagesHtml .= "<img src='{$encodedPath}' alt='{$file}' />";
            }
        }
    }

    return $imagesHtml !== '' ? $imagesHtml : null;
}

function getTableContent($folder) {
    $folderPath = realpath(__DIR__ . '/Data/' . urldecode($folder));
    if (file_exists($folderPath . DIRECTORY_SEPARATOR . 'table.txt')) {
        $columns = [];
        $rows = [];
        foreach (glob($folderPath . DIRECTORY_SEPARATOR . 'c*_*.txt') as $file) {
            preg_match('/c(\d+)_(.*)\.txt$/', basename($file), $matches);
            $columns[$matches[1]] = [
                'header' => $matches[2],
                'file' => $file
            ];
        }
        ksort($columns);
        foreach ($columns as $index => $column) {
            $content = file($column['file'], FILE_IGNORE_NEW_LINES);
            foreach ($content as $rowIndex => $line) {
                $rows[$rowIndex][$index] = $line;
            }
        }
        $tableHtml = '<table border="1"><thead><tr>';
        foreach ($columns as $column) {
            $tableHtml .= '<th>' . htmlspecialchars($column['header']) . '</th>';
        }
        $tableHtml .= '</tr></thead><tbody>';
        foreach ($rows as $row) {
            $counter = 0;
            $tableHtml .= '<tr>';
            foreach ($columns as $index => $column) {
                if ($counter > 0) {
                    $tableHtml .= '<td style="text-align:center">' . htmlspecialchars($row[$index] ?? '') . '</td>';
                } else {
                    $tableHtml .= '<td>' . htmlspecialchars($row[$index] ?? '') . '</td>';
                }
                $counter++;  
            }
            $tableHtml .= '</tr>';
        }
        $tableHtml .= '</tbody></table>';
        return $tableHtml;
    }
    return null;
}

if (isset($_GET['file'])) {
    echo getContent($_GET['file']);
} elseif (isset($_GET['folder'])) {
    $imagesContent = getImagesContent($_GET['folder']);
    if ($imagesContent) {
        echo $imagesContent;
    } else {
        $tableContent = getTableContent($_GET['folder']);
        if ($tableContent) {
            echo $tableContent;
        } else {
            echo getDefaultContent($_GET['folder']);
        }
    }
} else {
    echo getDefaultContent('#1 Welcome');
}
?>