<?php

/* Generated by chatGPT 4o */

function readDirectory($dir) {
    $result = [];
    $files = scandir($dir);
    natsort($files);

    foreach ($files as $file) {
        if ($file == '.' || $file == '..' || $file == 'additional.txt') continue;
        $filePath = $dir . DIRECTORY_SEPARATOR . $file;
        // Skip index.txt, images, table.txt, and c#_*.txt files
        if ($file == 'index.txt' || preg_match('/\.(png|jpg|jpeg|gif)$/i', $file) || $file == 'table.txt' || preg_match('/^c\d+_.*\.txt$/', $file)) continue;
        if (is_dir($filePath)) {
            $result[$file] = readDirectory($filePath);
        } else {
            $result[$file] = $filePath;
        }
    }

    return $result;
}

if (isset($_GET['folder'])) {
    $dataPath = realpath(__DIR__ . '/Data/' . urldecode($_GET['folder']));
    $subMenuData = readDirectory($dataPath);
    echo json_encode($subMenuData);
}
?>